language: node_js
node_js:
- '10'
cache:
  directories:
#  - ".cache"
before_install:
install:
- yarn install
- yarn list
before_script:
script:
- git --version
- node bin/tieba-sign cookie $bduss
- node bin/tieba-sign --hideUser
env:
  global:
  - CLONE_DEPTH=5
  - FORCE_COLOR=1
  - secure: >-
      jH/sOMjd1scBuSBQwbpF7yO554te1PhT5vrAhwhtmc0ALz0zDymlDoEBiyxYFOrCjYmkckMIBgk5wLzBRt48MpCVmtHBYNPCgJYG8lvUkyqyfkzCaxnoP7C2uCl0NdG8773nCxQH34CMixrAmfuvGhrDxe8+RV28Bxt52wnJWW8fauPEmIqP53Ryrm0qhQ3jf6Ja+YWUXLBmG/fTBXYKjcE8afVnDo6T0jvhsbAxgKq8sx9Ora+vDI4rf8oOsqL8F/0n1IcAayy0zSAz9DiWC1eNdEVvvFL5FvpGYJKEweESrlv0GY036T1inwHE6vNR2Wsnv2KoUV6maaciLRE57G7bc2+x22GkBlPVI2CGKG8dDiGk6ExIWW6fMH9jYhzy9z7Pdv9KuSU0ymybuhwjFeCFzqd2X1q2tIoehv+PLTUQ3aiEP3W/reF/WdzmoBkfu+J+PwnXVZ8WqS4SluQOneuCROCwNwoJK8ZVLHH5qTFBu8educSeT1vGP0MN3PSfoY85712cHamx3f8DUZj3CWz74Koj+Osh0VtqxgDj+yMLxIfIIAZhRK5H783Wiabna1BAerZNeLrqHEKVXXRgj2HaVhBVzgG3DD7wNZ80ywljHn23zIL0rS2ENHyro+BmwPCzV9wPOfjAJOB4tuEc/nFpcjn3PcLinmtfmx4UhYQ=
